### ISSUE TITLE
推荐些我常用的

### ISSUE THREAD

**Issue by s5s5** [shenzekun/useful-tools#6]
- [CSS3动画手册](http://caibaojian.com/demo/css3/animate/guide.html)
- [CSS ARROW PLEASE!](http://www.cssarrowplease.com/) (生成CSS小三角)
- [SVGOMG!](https://jakearchibald.github.io/svgomg/) (SVG图形压缩)
- [HTML Table Generator](http://www.tablesgenerator.com/html_tables) (HTML表格生成)
- [CSS3, please!](http://css3please.com/) (CSS3常用效果生成)
- [Carbon](https://carbon.now.sh/) (代码截图生成)
- [优图OCR](https://open.youtu.qq.com/#/open/experience/general) (各种OCR识别)
- [腾讯文档](https://docs.qq.com/) (在线协作各种文档)

**Comment by shenzekun** [comment]
赞，已添加，感谢：）
